site_name: Cultura Transparente 
nav:
  - Home: index.md
  - Sprints: sprints.md
  - Organização do Projeto: 
      - Aquitetura: arquitetura.md
      - Storymap: storymap.md
      - Protótipo: prototipo.md 
  - Como Executar?: comoexecutar.md
  - Como contribuir?: contribuir.md 

theme: material 

